apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "common.names.fullname" . }}-postinstall-job"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ template "common.names.chart" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ template "common.names.fullname" . }}-postinstall-hook"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: {{ template "common.names.chart" . }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "alpine:latest"
        command:
          - "chmod"
          - "-R"
          - "{{ .Values.armUID }}:{{ .Values.armGID }}"
          - "{{ .Values.appVolumeMounts.home.mountPath }}"
          - "{{ .Values.appVolumeMounts.media.mountPath }}"
          - "{{ .Values.appVolumeMounts.music.mountPath }}"
          - "{{ .Values.appVolumeMounts.logs.mountPath }}"
        volumeMounts: {{ include "common.storage.configureAppVolumeMountsInContainer" .Values | nindent 12 }}
      volumes: {{ include "common.storage.configureAppVolumes" .Values | nindent 8 }}
      backoffLimit: 9
