apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
description: Automatic ripping machine scripts
home: https://github.com/automatic-ripping-machine/automatic-ripping-machine
icon: https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/main/arm/ui/static/img/arm80.png?raw=true
keywords:
- automatic
- dvd
- ripper
- bluray
name: ripper
upstream_version: 2.6.12
version: 0.0.1
