# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The Image to use for ARM

image:
  repository: automaticrippingmachine/automatic-ripping-machine
  tag: 2.6.12
  pullPolicy: IfNotPresent

armUID: "1000"
armGID: "1000"

# Set the timezone of the plex server
timezone: "Etc/UTC"

# upgrade strategy type (e.g. Recreate or RollingUpdate)
updateStrategy: Recreate

hostNetwork: false

proxy:
  # This allows to set a proxy environment variable, which PMS uses to fetch the token and assets like movie cover
  enabled: false
  # http: "http://proxy:8080"
  # https: "https://proxy:8080"
  # noproxy: "localhost,127.0.0.1,10.96.0.0/12,10.244.0.0/12"

gpuConfiguration: {}

appVolumeMounts:
  config:
    emptyDir: true
    mountPath: /etc/arm/config
  home:
    emptyDir: true
    mountPath: /home/arm
  media:
    emptyDir: true
    mountPath: /home/arm/media
  logs:
    emptyDir: true
    mountPath: /home/arm/logs
  transcode:
    emptyDir: true
    mountPath: /home/arm/media/transcode
  music:
    emptyDir: true
    mountPath: /home/arm/media/Music
